[provider]
cluster = "localnet"
wallet = "/home/powerconstruct/.config/solana/id.json"

[programs.localnet]
prize_pool_contract = "GDtbF64JLEbuoGxRTrVob8wef28sByS8GZn4JzSBJTCW"

[scripts]
test = "mocha -t 1000000 tests/"
